Shader "Hidden/Post FX/Grain Generator" {
	Properties {
	}
	SubShader {
		Pass {
			ZClip Off
			ZTest Always
			ZWrite Off
			Cull Off
			GpuProgramID 35105
			Program "vp" {
				SubProgram "d3d9 " {
					"!!vs_3_0
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   row_major float4x4 unity_MatrixVP;
					//   row_major float4x4 unity_ObjectToWorld;
					//
					//
					// Registers:
					//
					//   Name                Reg   Size
					//   ------------------- ----- ----
					//   unity_ObjectToWorld c0       4
					//   unity_MatrixVP      c4       4
					//   _MainTex_ST         c8       1
					//
					
					    vs_3_0
					    def c9, 1, 0, 0, 0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1.xy
					    dcl_texcoord1 o2.xy
					    mad r0, v0.xyzx, c9.xxxy, c9.yyyx
					    dp4 r1.x, c0, r0
					    dp4 r1.y, c1, r0
					    dp4 r1.z, c2, r0
					    dp4 r1.w, c3, r0
					    dp4 r2.x, c4, r1
					    dp4 r2.y, c5, r1
					    dp4 r2.z, c6, r1
					    dp4 r2.w, c7, r1
					    mad o2.xy, v1, c8, c8.zwzw
					    mov o1.xy, v1
					    mad o0.xy, r2.w, c255, r2
					    mov o0.zw, r2
					
					// approximately 13 instruction slots used"
				}
				SubProgram "d3d11 " {
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xyzw        1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1     zw        1     NONE   float     zw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o1.zw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mad o1.zw, v1.xxxy, cb0[3].xxxy, cb0[3].zzzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d9 " {
					"!!ps_3_0
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float _Phase;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _Phase       c0       1
					//
					
					    ps_3_0
					    def c1, 192, -2, -1, 43758.5469
					    def c2, 12.9898005, 78.2330017, 0, -12
					    def c3, 0.159154937, 0.5, 6.28318548, -3.14159274
					    def c4, 0.0833333358, 0.0416666679, 0.166666672, 0.0625
					    def c5, 0, -2, -1, 1
					    def c6, 2, -2, -1, 0
					    dcl_texcoord v0.xy
					    frc r0.x, c0.x
					    mad r1, v0.xyxy, c1.x, r0.x
					    add r2, r1.zwzw, c1.yyzy
					    dp2add r2.x, r2, c2, c2.z
					    dp2add r2.y, r2.zwzw, c2, c2.z
					    mad r2.y, r2.y, c3.x, c3.y
					    frc r2.y, r2.y
					    mad r2.y, r2.y, c3.z, c3.w
					    sincos r3.y, r2.y
					    mul r2.y, r3.y, c1.w
					    mad r2.x, r2.x, c3.x, c3.y
					    frc r2.xy, r2
					    mad r2.x, r2.x, c3.z, c3.w
					    sincos r3.y, r2.x
					    mul r2.x, r3.y, c1.w
					    frc r2.x, r2.x
					    mad r2.x, r2.y, -c1.y, r2.x
					    mov r0.yzw, c5.xxyz
					    mad r3, v0.xyxy, c1.x, r0.yxxy
					    add r4, r0.xzxw, r3.xyxy
					    add r5, r0.zxwx, r3.zwzw
					    mad r0.xy, r0.x, c5.xwzw, c5.wxzw
					    dp2add r0.w, r4, c2, c2.z
					    dp2add r2.z, r4.zwzw, c2, c2.z
					    mad r2.z, r2.z, c3.x, c3.y
					    frc r2.z, r2.z
					    mad r2.z, r2.z, c3.z, c3.w
					    sincos r4.y, r2.z
					    mul r2.z, r4.y, c1.w
					    mad r0.w, r0.w, c3.x, c3.y
					    frc r0.w, r0.w
					    mad r0.w, r0.w, c3.z, c3.w
					    sincos r4.y, r0.w
					    mul r0.w, r4.y, c1.w
					    frc r0.w, r0.w
					    add r2.x, r0.w, r2.x
					    add r4, r1.zwzw, c1.yzzz
					    dp2add r2.w, r4, c2, c2.z
					    dp2add r4.x, r4.zwzw, c2, c2.z
					    mad r4.x, r4.x, c3.x, c3.y
					    frc r4.x, r4.x
					    mad r4.x, r4.x, c3.z, c3.w
					    sincos r6.y, r4.x
					    mul r4.x, r6.y, c1.w
					    frc r4.x, r4.x
					    mad r2.w, r2.w, c3.x, c3.y
					    frc r2.zw, r2
					    mad r2.w, r2.w, c3.z, c3.w
					    sincos r6.y, r2.w
					    mul r2.w, r6.y, c1.w
					    frc r2.w, r2.w
					    mad r2.x, r2.w, -c1.y, r2.x
					    mad r2.w, r4.x, -c1.y, r2.w
					    add r2.w, r2.z, r2.w
					    mad r2.x, r4.x, c2.w, r2.x
					    mad r2.x, r2.z, -c1.y, r2.x
					    dp2add r4.y, r5, c2, c2.z
					    dp2add r4.z, r5.zwzw, c2, c2.z
					    mad r4.z, r4.z, c3.x, c3.y
					    frc r4.z, r4.z
					    mad r4.z, r4.z, c3.z, c3.w
					    sincos r5.y, r4.z
					    mul r4.z, r5.y, c1.w
					    mad r4.y, r4.y, c3.x, c3.y
					    frc r4.yz, r4
					    mad r4.y, r4.y, c3.z, c3.w
					    sincos r5.y, r4.y
					    mul r4.y, r5.y, c1.w
					    frc r4.y, r4.y
					    add r2.x, r2.x, r4.y
					    mad r2.x, r4.z, -c1.y, r2.x
					    dp2add r4.w, r1.zwzw, c2, c2.z
					    mad r4.w, r4.w, c3.x, c3.y
					    frc r4.w, r4.w
					    mad r4.w, r4.w, c3.z, c3.w
					    sincos r5.y, r4.w
					    mul r4.w, r5.y, c1.w
					    frc r4.w, r4.w
					    mad r2.y, r0.w, -c1.y, r2.y
					    add r5, r1.zwzw, c5.wywz
					    dp2add r5.x, r5, c2, c2.z
					    dp2add r5.y, r5.zwzw, c2, c2.z
					    mad r5.y, r5.y, c3.x, c3.y
					    frc r5.y, r5.y
					    mad r5.y, r5.y, c3.z, c3.w
					    sincos r6.y, r5.y
					    mul r5.y, r6.y, c1.w
					    mad r5.x, r5.x, c3.x, c3.y
					    frc r5.xy, r5
					    mad r5.x, r5.x, c3.z, c3.w
					    sincos r6.y, r5.x
					    mul r5.x, r6.y, c1.w
					    frc r5.x, r5.x
					    add r2.y, r2.y, r5.x
					    mad r0.w, r5.x, -c1.y, r0.w
					    mad r2.y, r4.x, -c1.y, r2.y
					    mad r4.x, r2.z, -c1.y, r4.x
					    add r4.x, r5.y, r4.x
					    mad r4.x, r4.z, -c1.y, r4.x
					    mad r4.x, r4.w, c2.w, r4.x
					    mad r2.y, r2.z, c2.w, r2.y
					    mad r2.y, r5.y, -c1.y, r2.y
					    add r2.xy, r4.wzzw, r2
					    mad r2.y, r4.w, -c1.y, r2.y
					    add r6, r0.xyyx, r3.zwxy
					    dp2add r0.x, r6, c2, c2.z
					    dp2add r5.x, r6.zwzw, c2, c2.z
					    mad r5.x, r5.x, c3.x, c3.y
					    frc r5.x, r5.x
					    mad r5.x, r5.x, c3.z, c3.w
					    sincos r6.y, r5.x
					    mul r5.x, r6.y, c1.w
					    frc r5.x, r5.x
					    mad r0.x, r0.x, c3.x, c3.y
					    frc r0.x, r0.x
					    mad r0.x, r0.x, c3.z, c3.w
					    sincos r6.y, r0.x
					    mul r0.x, r6.y, c1.w
					    frc r0.x, r0.x
					    add r2.y, r0.x, r2.y
					    mul r2.y, r2.y, c4.x
					    mad r2.x, r2.x, c4.y, r2.y
					    mov r0.z, -c1.y
					    add r3, r0.zyyz, r3.zwxy
					    dp2add r0.y, r3, c2, c2.z
					    dp2add r0.z, r3.zwzw, c2, c2.z
					    mad r0.z, r0.z, c3.x, c3.y
					    frc r0.z, r0.z
					    mad r0.z, r0.z, c3.z, c3.w
					    sincos r3.y, r0.z
					    mul r0.z, r3.y, c1.w
					    mad r0.y, r0.y, c3.x, c3.y
					    frc r0.yz, r0
					    mad r0.y, r0.y, c3.z, c3.w
					    sincos r3.y, r0.y
					    mul r0.y, r3.y, c1.w
					    frc r0.y, r0.y
					    add r3, r1.zwzw, c6.xyxz
					    dp2add r2.y, r3, c2, c2.z
					    dp2add r3.x, r3.zwzw, c2, c2.z
					    mad r3.x, r3.x, c3.x, c3.y
					    frc r3.x, r3.x
					    mad r3.x, r3.x, c3.z, c3.w
					    sincos r6.y, r3.x
					    mul r3.x, r6.y, c1.w
					    frc r3.x, r3.x
					    mad r2.y, r2.y, c3.x, c3.y
					    frc r2.y, r2.y
					    mad r2.y, r2.y, c3.z, c3.w
					    sincos r6.y, r2.y
					    mul r2.y, r6.y, c1.w
					    frc r2.y, r2.y
					    add r0.w, r0.w, r2.y
					    mad r0.w, r2.z, -c1.y, r0.w
					    mad r2.y, r5.y, -c1.y, r2.z
					    mad r0.w, r5.y, c2.w, r0.w
					    mad r0.w, r3.x, -c1.y, r0.w
					    add r2.y, r3.x, r2.y
					    mad r2.y, r4.w, -c1.y, r2.y
					    mad r2.y, r0.x, c2.w, r2.y
					    mad r2.y, r0.y, -c1.y, r2.y
					    add r0.w, r4.w, r0.w
					    mad r0.w, r0.x, -c1.y, r0.w
					    add r0.w, r0.y, r0.w
					    mad r0.w, r0.w, c4.y, r2.x
					    mad r2.x, r4.y, -c1.y, r2.w
					    mad r2.z, r4.z, -c1.y, r4.y
					    add r2.z, r4.w, r2.z
					    mad r2.x, r4.z, c2.w, r2.x
					    mad r2.w, r4.w, -c1.y, r4.z
					    add r2.w, r0.x, r2.w
					    mad r2.x, r4.w, -c1.y, r2.x
					    mad r3.x, r0.x, -c1.y, r4.w
					    mad r0.x, r0.x, -c1.y, r4.x
					    add r0.y, r0.y, r3.x
					    mad r0.y, r5.x, -c1.y, r0.y
					    add r3, r1.zwzw, c5.ywzw
					    dp2add r3.x, r3, c2, c2.z
					    dp2add r3.y, r3.zwzw, c2, c2.z
					    mad r3.y, r3.y, c3.x, c3.y
					    frc r3.y, r3.y
					    mad r3.y, r3.y, c3.z, c3.w
					    sincos r4.y, r3.y
					    mul r3.y, r4.y, c1.w
					    mad r3.x, r3.x, c3.x, c3.y
					    frc r3.xy, r3
					    mad r3.x, r3.x, c3.z, c3.w
					    sincos r4.y, r3.x
					    mul r3.x, r4.y, c1.w
					    frc r3.x, r3.x
					    add r2.x, r2.x, r3.x
					    mad r2.z, r3.x, -c1.y, r2.z
					    mad r2.z, r3.y, c2.w, r2.z
					    mad r2.z, r5.x, -c1.y, r2.z
					    mad r2.x, r3.y, -c1.y, r2.x
					    add r2.xy, r5.x, r2
					    mad r0.w, r2.x, c4.x, r0.w
					    add r0.x, r0.x, r3.y
					    mad r2.x, r3.y, -c1.y, r2.w
					    mad r2.x, r5.x, c2.w, r2.x
					    mad r0.x, r5.x, -c1.y, r0.x
					    add r3, r1.zwzw, -c1.zzyz
					    dp2add r2.w, r3, c2, c2.z
					    dp2add r3.x, r3.zwzw, c2, c2.z
					    mad r3.x, r3.x, c3.x, c3.y
					    frc r3.x, r3.x
					    mad r3.x, r3.x, c3.z, c3.w
					    sincos r4.y, r3.x
					    mul r3.x, r4.y, c1.w
					    frc r3.x, r3.x
					    mad r2.w, r2.w, c3.x, c3.y
					    frc r2.w, r2.w
					    mad r2.w, r2.w, c3.z, c3.w
					    sincos r4.y, r2.w
					    mul r2.w, r4.y, c1.w
					    frc r2.w, r2.w
					    add r0.x, r0.x, r2.w
					    mad r0.x, r0.x, c4.z, r0.w
					    mad r0.w, r2.w, -c1.y, r2.y
					    add r0.w, r3.x, r0.w
					    mad r0.x, r0.w, c4.x, r0.x
					    add r4, r1.zwzw, c6.yxzx
					    add r1, r1, -c1.zyyy
					    dp2add r0.w, r4, c2, c2.z
					    dp2add r2.y, r4.zwzw, c2, c2.z
					    mad r2.y, r2.y, c3.x, c3.y
					    frc r2.y, r2.y
					    mad r2.y, r2.y, c3.z, c3.w
					    sincos r4.y, r2.y
					    mul r2.y, r4.y, c1.w
					    frc r2.y, r2.y
					    mad r0.w, r0.w, c3.x, c3.y
					    frc r0.w, r0.w
					    mad r0.w, r0.w, c3.z, c3.w
					    sincos r4.y, r0.w
					    mul r0.w, r4.y, c1.w
					    frc r0.w, r0.w
					    add r0.w, r0.w, r2.z
					    mad r0.w, r2.y, -c1.y, r0.w
					    add r0.w, r0.z, r0.w
					    mad r0.x, r0.w, c4.y, r0.x
					    mad r0.w, r2.w, -c1.y, r2.x
					    mad r0.y, r2.w, c2.w, r0.y
					    mad r0.y, r3.x, -c1.y, r0.y
					    add r0.y, r0.z, r0.y
					    add r0.w, r2.y, r0.w
					    mad r0.z, r0.z, -c1.y, r0.w
					    dp2add r0.w, r1, c2, c2.z
					    dp2add r1.x, r1.zwzw, c2, c2.z
					    mad r1.x, r1.x, c3.x, c3.y
					    frc r1.x, r1.x
					    mad r1.x, r1.x, c3.z, c3.w
					    sincos r2.y, r1.x
					    mul r1.x, r2.y, c1.w
					    frc r1.x, r1.x
					    mad r0.w, r0.w, c3.x, c3.y
					    frc r0.w, r0.w
					    mad r0.w, r0.w, c3.z, c3.w
					    sincos r2.y, r0.w
					    mul r0.w, r2.y, c1.w
					    frc r0.w, r0.w
					    add r0.z, r0.w, r0.z
					    mad r0.y, r0.w, -c1.y, r0.y
					    add r0.y, r1.x, r0.y
					    mad r0.x, r0.z, c4.x, r0.x
					    mad r0.x, r0.y, c4.y, r0.x
					    mul oC0.xyz, r0.x, c4.w
					    mov oC0.w, -c1.z
					
					// approximately 468 instruction slots used"
				}
				SubProgram "d3d11 " {
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1     zw        1     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 7
					frc r0.y, cb0[4].x
					mad r1.xyzw, v1.xyxy, l(192.000000, 192.000000, 192.000000, 192.000000), r0.yyyy
					add r2.xyzw, r1.zwzw, l(-2.000000, -2.000000, -1.000000, -2.000000)
					dp2 r2.x, r2.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r2.y, r2.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r2.xy, null, r2.xyxx
					mul r2.xy, r2.xyxx, l(43758.546875, 43758.546875, 0.000000, 0.000000)
					frc r2.xy, r2.xyxx
					mad r2.x, r2.y, l(2.000000), r2.x
					mov r0.xzw, l(0,0,-2.000000,-1.000000)
					mad r3.xyzw, v1.xyxy, l(192.000000, 192.000000, 192.000000, 192.000000), r0.xyyx
					add r4.xyzw, r0.yzyw, r3.xyxy
					add r5.xyzw, r0.zywy, r3.zwzw
					dp2 r0.w, r4.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r2.z, r4.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r2.z, null, r2.z
					mul r2.z, r2.z, l(43758.546875)
					sincos r0.w, null, r0.w
					mul r0.w, r0.w, l(43758.546875)
					frc r0.w, r0.w
					add r2.x, r0.w, r2.x
					add r4.xyzw, r1.zwzw, l(-2.000000, -1.000000, -1.000000, -1.000000)
					dp2 r2.w, r4.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r4.x, r4.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r4.x, null, r4.x
					mul r4.x, r4.x, l(43758.546875)
					frc r4.x, r4.x
					sincos r2.w, null, r2.w
					mul r2.w, r2.w, l(43758.546875)
					frc r2.zw, r2.zzzw
					mad r2.x, r2.w, l(2.000000), r2.x
					mad r2.w, r4.x, l(2.000000), r2.w
					mad r2.x, r4.x, l(-12.000000), r2.x
					mad r2.x, r2.z, l(2.000000), r2.x
					dp2 r4.y, r5.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r4.z, r5.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r4.yz, null, r4.yyzy
					mul r4.yz, r4.yyzy, l(0.000000, 43758.546875, 43758.546875, 0.000000)
					frc r4.yz, r4.yyzy
					add r2.x, r2.x, r4.y
					mad r2.x, r4.z, l(2.000000), r2.x
					dp2 r4.w, r1.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r4.w, null, r4.w
					mul r4.w, r4.w, l(43758.546875)
					frc r4.w, r4.w
					mad r2.y, r0.w, l(2.000000), r2.y
					add r5.xyzw, r1.zwzw, l(1.000000, -2.000000, 1.000000, -1.000000)
					dp2 r5.x, r5.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r5.y, r5.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r5.xy, null, r5.xyxx
					mul r5.xy, r5.xyxx, l(43758.546875, 43758.546875, 0.000000, 0.000000)
					frc r5.xy, r5.xyxx
					add r2.y, r2.y, r5.x
					mad r0.w, r5.x, l(2.000000), r0.w
					mad r2.y, r4.x, l(2.000000), r2.y
					mad r4.x, r2.z, l(2.000000), r4.x
					add r4.x, r5.y, r4.x
					mad r4.x, r4.z, l(2.000000), r4.x
					mad r4.x, r4.w, l(-12.000000), r4.x
					mad r2.y, r2.z, l(-12.000000), r2.y
					mad r2.y, r5.y, l(2.000000), r2.y
					add r2.xy, r4.wzww, r2.xyxx
					mad r2.y, r4.w, l(2.000000), r2.y
					mov r0.xz, l(1.000000,0,2.000000,0)
					add r6.xyzw, r0.xyzy, r3.zwzw
					add r3.xyzw, r0.yxyz, r3.xyxy
					dp2 r0.x, r6.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r0.y, r6.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r0.xy, null, r0.xyxx
					mul r0.xy, r0.xyxx, l(43758.546875, 43758.546875, 0.000000, 0.000000)
					frc r0.xy, r0.xyxx
					add r0.z, r0.x, r2.y
					mul r0.z, r0.z, l(0.083333)
					mad r0.z, r2.x, l(0.041667), r0.z
					add r6.xyzw, r1.zwzw, l(2.000000, -2.000000, 2.000000, -1.000000)
					dp2 r2.x, r6.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r2.y, r6.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r2.xy, null, r2.xyxx
					mul r2.xy, r2.xyxx, l(43758.546875, 43758.546875, 0.000000, 0.000000)
					frc r2.xy, r2.xyxx
					add r0.w, r0.w, r2.x
					mad r0.w, r2.z, l(2.000000), r0.w
					mad r2.x, r5.y, l(2.000000), r2.z
					mad r0.w, r5.y, l(-12.000000), r0.w
					mad r0.w, r2.y, l(2.000000), r0.w
					add r2.xw, r2.yyyz, r2.xxxw
					mad r2.x, r4.w, l(2.000000), r2.x
					mad r2.x, r0.x, l(-12.000000), r2.x
					mad r2.x, r0.y, l(2.000000), r2.x
					add r0.w, r4.w, r0.w
					mad r0.w, r0.x, l(2.000000), r0.w
					add r0.w, r0.y, r0.w
					mad r0.z, r0.w, l(0.041667), r0.z
					mad r0.w, r4.y, l(2.000000), r2.w
					mad r2.y, r4.z, l(2.000000), r4.y
					add r2.y, r4.w, r2.y
					mad r0.w, r4.z, l(-12.000000), r0.w
					mad r2.z, r4.w, l(2.000000), r4.z
					add r2.z, r0.x, r2.z
					mad r0.w, r4.w, l(2.000000), r0.w
					mad r2.w, r0.x, l(2.000000), r4.w
					mad r0.x, r0.x, l(2.000000), r4.x
					add r0.y, r0.y, r2.w
					add r4.xyzw, r1.zwzw, l(-2.000000, 1.000000, -1.000000, 1.000000)
					dp2 r2.w, r4.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r4.x, r4.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r4.x, null, r4.x
					mul r4.x, r4.x, l(43758.546875)
					frc r4.x, r4.x
					sincos r2.w, null, r2.w
					mul r2.w, r2.w, l(43758.546875)
					frc r2.w, r2.w
					add r0.w, r0.w, r2.w
					mad r2.y, r2.w, l(2.000000), r2.y
					mad r2.y, r4.x, l(-12.000000), r2.y
					mad r0.w, r4.x, l(2.000000), r0.w
					dp2 r2.w, r3.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r3.x, r3.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r3.x, null, r3.x
					mul r3.x, r3.x, l(43758.546875)
					sincos r2.w, null, r2.w
					mul r2.w, r2.w, l(43758.546875)
					frc r2.w, r2.w
					add r0.w, r0.w, r2.w
					mad r0.z, r0.w, l(0.083333), r0.z
					add r0.x, r0.x, r4.x
					mad r0.w, r4.x, l(2.000000), r2.z
					mad r0.w, r2.w, l(-12.000000), r0.w
					mad r0.x, r2.w, l(2.000000), r0.x
					add r4.xyzw, r1.zwzw, l(1.000000, 1.000000, 2.000000, 1.000000)
					dp2 r2.z, r4.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r3.y, r4.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r3.y, null, r3.y
					mul r3.y, r3.y, l(43758.546875)
					frc r3.xy, r3.xyxx
					sincos r2.z, null, r2.z
					mul r2.z, r2.z, l(43758.546875)
					frc r2.z, r2.z
					add r0.x, r0.x, r2.z
					mad r0.x, r0.x, l(0.166667), r0.z
					add r0.z, r2.w, r2.x
					mad r0.z, r2.z, l(2.000000), r0.z
					add r0.z, r3.y, r0.z
					mad r0.x, r0.z, l(0.083333), r0.x
					mad r0.z, r2.w, l(2.000000), r2.y
					mad r0.y, r2.w, l(2.000000), r0.y
					mad r0.y, r2.z, l(-12.000000), r0.y
					mad r0.w, r2.z, l(2.000000), r0.w
					mad r0.y, r3.y, l(2.000000), r0.y
					add r2.xyzw, r1.zwzw, l(-2.000000, 2.000000, -1.000000, 2.000000)
					add r1.xyzw, r1.xyzw, l(1.000000, 2.000000, 2.000000, 2.000000)
					dp2 r2.x, r2.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r2.y, r2.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r2.xy, null, r2.xyxx
					mul r2.xy, r2.xyxx, l(43758.546875, 43758.546875, 0.000000, 0.000000)
					frc r2.xy, r2.xyxx
					add r0.zw, r0.zzzw, r2.xxxy
					mad r0.z, r2.y, l(2.000000), r0.z
					mad r0.w, r3.x, l(2.000000), r0.w
					add r0.yz, r3.xxxx, r0.yyzy
					mad r0.x, r0.z, l(0.041667), r0.x
					dp2 r0.z, r1.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r1.x, r1.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r1.x, null, r1.x
					mul r1.x, r1.x, l(43758.546875)
					frc r1.x, r1.x
					sincos r0.z, null, r0.z
					mul r0.z, r0.z, l(43758.546875)
					frc r0.z, r0.z
					add r0.w, r0.z, r0.w
					mad r0.y, r0.z, l(2.000000), r0.y
					add r0.y, r1.x, r0.y
					mad r0.x, r0.w, l(0.083333), r0.x
					mad r0.x, r0.y, l(0.041667), r0.x
					mul o0.xyz, r0.xxxx, l(0.062500, 0.062500, 0.062500, 0.000000)
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
		Pass {
			ZClip Off
			ZTest Always
			ZWrite Off
			Cull Off
			GpuProgramID 72783
			Program "vp" {
				SubProgram "d3d9 " {
					"!!vs_3_0
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   row_major float4x4 unity_MatrixVP;
					//   row_major float4x4 unity_ObjectToWorld;
					//
					//
					// Registers:
					//
					//   Name                Reg   Size
					//   ------------------- ----- ----
					//   unity_ObjectToWorld c0       4
					//   unity_MatrixVP      c4       4
					//   _MainTex_ST         c8       1
					//
					
					    vs_3_0
					    def c9, 1, 0, 0, 0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1.xy
					    dcl_texcoord1 o2.xy
					    mad r0, v0.xyzx, c9.xxxy, c9.yyyx
					    dp4 r1.x, c0, r0
					    dp4 r1.y, c1, r0
					    dp4 r1.z, c2, r0
					    dp4 r1.w, c3, r0
					    dp4 r2.x, c4, r1
					    dp4 r2.y, c5, r1
					    dp4 r2.z, c6, r1
					    dp4 r2.w, c7, r1
					    mad o2.xy, v1, c8, c8.zwzw
					    mov o1.xy, v1
					    mad o0.xy, r2.w, c255, r2
					    mov o0.zw, r2
					
					// approximately 13 instruction slots used"
				}
				SubProgram "d3d11 " {
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xyzw        1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1     zw        1     NONE   float     zw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o1.zw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mad o1.zw, v1.xxxy, cb0[3].xxxy, cb0[3].zzzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d9 " {
					"!!ps_3_0
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float _Phase;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _Phase       c0       1
					//
					
					    ps_3_0
					    def c1, 192, -2, -1, 0
					    def c2, 12.9898005, 78.2330017, 0, -12
					    def c3, 0.0700000003, 0.109999999, 0.129999995, 43758.5469
					    def c4, 0.159154937, 0.5, 6.28318548, -3.14159274
					    def c5, 0.0833333358, 0.0416666679, 0.166666672, 0.0625
					    def c6, 192, 1, -2, -1
					    def c7, 1, 0, 2, -2
					    def c8, 192, 2, -1, 0
					    def c9, 192, 2, 1, -2
					    dcl_texcoord v0.xy
					    mad r0, v0.xyxy, c1.x, c1.yyzz
					    frc r1.x, c0.x
					    mad r2, r1.x, c3.x, r0
					    dp2add r1.y, r2, c2, c2.z
					    dp2add r1.z, r2.zwzw, c2, c2.z
					    mad r1.z, r1.z, c4.x, c4.y
					    frc r1.z, r1.z
					    mad r1.z, r1.z, c4.z, c4.w
					    sincos r2.y, r1.z
					    mul r1.z, r2.y, c3.w
					    mad r1.y, r1.y, c4.x, c4.y
					    frc r1.yz, r1
					    mad r1.y, r1.y, c4.z, c4.w
					    sincos r2.y, r1.y
					    mul r1.y, r2.y, c3.w
					    mad r2, v0.xyxy, c1.x, c1.zywy
					    mad r3, r1.x, c3.x, r2
					    dp2add r1.w, r3, c2, c2.z
					    dp2add r3.x, r3.zwzw, c2, c2.z
					    mad r3.x, r3.x, c4.x, c4.y
					    frc r3.x, r3.x
					    mad r3.x, r3.x, c4.z, c4.w
					    sincos r4.y, r3.x
					    mul r3.x, r4.y, c3.w
					    frc r3.x, r3.x
					    mad r1.w, r1.w, c4.x, c4.y
					    frc r1.yw, r1
					    mad r1.w, r1.w, c4.z, c4.w
					    sincos r4.y, r1.w
					    mul r1.w, r4.y, c3.w
					    frc r1.w, r1.w
					    mad r1.y, r1.w, -c1.y, r1.y
					    mad r1.w, r3.x, -c1.y, r1.w
					    add r1.y, r3.x, r1.y
					    mad r4, v0.xyxy, c1.x, c1.yzwz
					    mad r5, r1.x, c3.x, r4
					    dp2add r3.y, r5, c2, c2.z
					    dp2add r3.z, r5.zwzw, c2, c2.z
					    mad r3.z, r3.z, c4.x, c4.y
					    frc r3.z, r3.z
					    mad r3.z, r3.z, c4.z, c4.w
					    sincos r5.y, r3.z
					    mul r3.z, r5.y, c3.w
					    mad r3.y, r3.y, c4.x, c4.y
					    frc r3.yz, r3
					    mad r3.y, r3.y, c4.z, c4.w
					    sincos r5.y, r3.y
					    mul r3.y, r5.y, c3.w
					    frc r3.y, r3.y
					    mad r1.y, r3.y, -c1.y, r1.y
					    mad r3.y, r1.z, -c1.y, r3.y
					    add r3.y, r3.z, r3.y
					    mad r1.y, r1.z, c2.w, r1.y
					    mad r1.y, r3.z, -c1.y, r1.y
					    mad r5, v0.xyxy, c1.x, c1.ywzw
					    mad r6, r1.x, c3.x, r5
					    dp2add r3.w, r6, c2, c2.z
					    dp2add r6.x, r6.zwzw, c2, c2.z
					    mad r6.x, r6.x, c4.x, c4.y
					    frc r6.x, r6.x
					    mad r6.x, r6.x, c4.z, c4.w
					    sincos r7.y, r6.x
					    mul r6.x, r7.y, c3.w
					    frc r6.x, r6.x
					    mad r3.w, r3.w, c4.x, c4.y
					    frc r3.w, r3.w
					    mad r3.w, r3.w, c4.z, c4.w
					    sincos r7.y, r3.w
					    mul r3.w, r7.y, c3.w
					    frc r3.w, r3.w
					    add r1.y, r1.y, r3.w
					    mad r1.y, r6.x, -c1.y, r1.y
					    mul r6.yzw, r1.x, c3.xxyz
					    mad r7, v0.xyxy, c1.x, r6.yyzz
					    mad r6.yz, v0.xxyw, c1.x, r6.w
					    dp2add r6.y, r6.yzzw, c2, c2.z
					    mad r6.y, r6.y, c4.x, c4.y
					    frc r6.y, r6.y
					    mad r6.y, r6.y, c4.z, c4.w
					    sincos r8.y, r6.y
					    mul r6.y, r8.y, c3.w
					    dp2add r6.z, r7, c2, c2.z
					    dp2add r6.w, r7.zwzw, c2, c2.z
					    mad r6.w, r6.w, c4.x, c4.y
					    frc r6.yw, r6
					    mad r6.w, r6.w, c4.z, c4.w
					    sincos r7.y, r6.w
					    mul r6.w, r7.y, c3.w
					    mad r6.z, r6.z, c4.x, c4.y
					    frc r6.zw, r6
					    mad r6.z, r6.z, c4.z, c4.w
					    sincos r7.y, r6.z
					    mul r6.z, r7.y, c3.w
					    frc r6.z, r6.z
					    mad r7, v0.xyxy, c6.x, c6.yzyw
					    mad r8, r1.x, c3.x, r7
					    dp2add r8.x, r8, c2, c2.z
					    dp2add r8.y, r8.zwzw, c2, c2.z
					    mad r8.y, r8.y, c4.x, c4.y
					    frc r8.y, r8.y
					    mad r8.y, r8.y, c4.z, c4.w
					    sincos r9.y, r8.y
					    mul r8.y, r9.y, c3.w
					    mad r8.x, r8.x, c4.x, c4.y
					    frc r8.xy, r8
					    mad r8.x, r8.x, c4.z, c4.w
					    sincos r9.y, r8.x
					    mul r8.x, r9.y, c3.w
					    frc r8.x, r8.x
					    add r1.w, r1.w, r8.x
					    mad r3.x, r8.x, -c1.y, r3.x
					    mad r1.w, r1.z, -c1.y, r1.w
					    mad r1.z, r3.z, -c1.y, r1.z
					    add r1.z, r8.y, r1.z
					    mad r1.z, r6.x, -c1.y, r1.z
					    mad r1.z, r6.z, c2.w, r1.z
					    mad r1.w, r3.z, c2.w, r1.w
					    mad r1.w, r8.y, -c1.y, r1.w
					    add r1.yw, r6.xzzx, r1
					    mad r1.w, r6.z, -c1.y, r1.w
					    mov r8.x, c1.x
					    mad r9, v0.xyxy, r8.x, c7
					    mad r10, r1.x, c3.x, r9
					    dp2add r8.x, r10, c2, c2.z
					    dp2add r8.z, r10.zwzw, c2, c2.z
					    mad r8.z, r8.z, c4.x, c4.y
					    frc r8.z, r8.z
					    mad r8.z, r8.z, c4.z, c4.w
					    sincos r10.y, r8.z
					    mul r8.z, r10.y, c3.w
					    frc r8.z, r8.z
					    add r3.x, r3.x, r8.z
					    mad r3.x, r3.z, -c1.y, r3.x
					    mad r3.z, r8.y, -c1.y, r3.z
					    mad r3.x, r8.y, c2.w, r3.x
					    mad r8.x, r8.x, c4.x, c4.y
					    frc r8.x, r8.x
					    mad r8.x, r8.x, c4.z, c4.w
					    sincos r10.y, r8.x
					    mul r8.x, r10.y, c3.w
					    frc r8.x, r8.x
					    add r1.w, r1.w, r8.x
					    mul r1.w, r1.w, c5.x
					    mad r1.y, r1.y, c5.y, r1.w
					    mad r10, v0.xyxy, c8.x, c8.yzyw
					    mad r11, r1.x, c3.x, r10
					    dp2add r1.w, r11, c2, c2.z
					    dp2add r8.y, r11.zwzw, c2, c2.z
					    mad r8.y, r8.y, c4.x, c4.y
					    frc r8.y, r8.y
					    mad r8.y, r8.y, c4.z, c4.w
					    sincos r11.y, r8.y
					    mul r8.y, r11.y, c3.w
					    frc r8.y, r8.y
					    mad r1.w, r1.w, c4.x, c4.y
					    frc r1.w, r1.w
					    mad r1.w, r1.w, c4.z, c4.w
					    sincos r11.y, r1.w
					    mul r1.w, r11.y, c3.w
					    frc r1.w, r1.w
					    mad r3.x, r1.w, -c1.y, r3.x
					    add r1.w, r1.w, r3.z
					    mad r1.w, r6.z, -c1.y, r1.w
					    mad r1.w, r8.x, c2.w, r1.w
					    mad r1.w, r8.y, -c1.y, r1.w
					    add r3.x, r6.z, r3.x
					    mad r3.x, r8.x, -c1.y, r3.x
					    add r3.x, r8.y, r3.x
					    mad r1.y, r3.x, c5.y, r1.y
					    mad r3.x, r3.w, -c1.y, r3.y
					    mad r3.y, r6.x, -c1.y, r3.w
					    add r3.y, r6.z, r3.y
					    mad r3.x, r6.x, c2.w, r3.x
					    mad r3.z, r6.z, -c1.y, r6.x
					    mad r3.x, r6.z, -c1.y, r3.x
					    mad r3.w, r8.x, -c1.y, r6.z
					    mad r1.z, r8.x, -c1.y, r1.z
					    add r3.zw, r8.xyxy, r3
					    mad r8, v0.xyxy, c6.x, c6.zywy
					    mad r11, r1.x, c3.x, r8
					    dp2add r6.x, r11, c2, c2.z
					    dp2add r6.z, r11.zwzw, c2, c2.z
					    mad r6.z, r6.z, c4.x, c4.y
					    frc r6.z, r6.z
					    mad r6.z, r6.z, c4.z, c4.w
					    sincos r11.y, r6.z
					    mul r6.z, r11.y, c3.w
					    mad r6.x, r6.x, c4.x, c4.y
					    frc r6.xz, r6
					    mad r6.x, r6.x, c4.z, c4.w
					    sincos r11.y, r6.x
					    mul r6.x, r11.y, c3.w
					    frc r6.x, r6.x
					    add r3.x, r3.x, r6.x
					    mad r3.y, r6.x, -c1.y, r3.y
					    mad r3.y, r6.z, c2.w, r3.y
					    mad r3.x, r6.z, -c1.y, r3.x
					    mad r11, v0.xyxy, c1_abs.x, c1_abs.wzzz
					    mad r12, r1.x, c3.x, r11
					    dp2add r6.x, r12, c2, c2.z
					    dp2add r12.x, r12.zwzw, c2, c2.z
					    mad r12.x, r12.x, c4.x, c4.y
					    frc r12.x, r12.x
					    mad r12.x, r12.x, c4.z, c4.w
					    sincos r13.y, r12.x
					    mul r12.x, r13.y, c3.w
					    frc r12.x, r12.x
					    mad r6.x, r6.x, c4.x, c4.y
					    frc r6.x, r6.x
					    mad r6.x, r6.x, c4.z, c4.w
					    sincos r13.y, r6.x
					    mul r6.x, r13.y, c3.w
					    frc r6.x, r6.x
					    add r3.x, r3.x, r6.x
					    mad r1.y, r3.x, c5.x, r1.y
					    add r1.z, r1.z, r6.z
					    mad r3.x, r6.z, -c1.y, r3.z
					    mad r3.x, r6.x, c2.w, r3.x
					    mad r3.x, r12.x, -c1.y, r3.x
					    mad r1.z, r6.x, -c1.y, r1.z
					    add r1.z, r12.x, r1.z
					    mad r1.y, r1.z, c5.z, r1.y
					    add r1.z, r1.w, r6.x
					    mad r1.z, r12.x, -c1.y, r1.z
					    mad r13, v0.xyxy, c9.x, c9.yzwy
					    mad r14, r1.x, c3.x, r13
					    dp2add r1.w, r14, c2, c2.z
					    dp2add r3.z, r14.zwzw, c2, c2.z
					    mad r3.z, r3.z, c4.x, c4.y
					    frc r3.z, r3.z
					    mad r3.z, r3.z, c4.z, c4.w
					    sincos r14.y, r3.z
					    mul r3.z, r14.y, c3.w
					    frc r3.z, r3.z
					    mad r1.w, r1.w, c4.x, c4.y
					    frc r1.w, r1.w
					    mad r1.w, r1.w, c4.z, c4.w
					    sincos r14.y, r1.w
					    mul r1.w, r14.y, c3.w
					    frc r1.w, r1.w
					    add r1.z, r1.w, r1.z
					    mad r1.y, r1.z, c5.x, r1.y
					    mad r1.z, r6.x, -c1.y, r3.y
					    mad r3.y, r6.x, -c1.y, r3.w
					    mad r3.y, r12.x, c2.w, r3.y
					    mad r1.w, r1.w, -c1.y, r3.y
					    add r1.z, r3.z, r1.z
					    mad r12, v0.xyxy, c8.x, c8.zywy
					    mad r14, r1.x, c3.x, r12
					    dp2add r3.y, r14, c2, c2.z
					    dp2add r3.z, r14.zwzw, c2, c2.z
					    mad r3.z, r3.z, c4.x, c4.y
					    frc r3.z, r3.z
					    mad r3.z, r3.z, c4.z, c4.w
					    sincos r14.y, r3.z
					    mul r3.z, r14.y, c3.w
					    mad r3.y, r3.y, c4.x, c4.y
					    frc r3.yz, r3
					    mad r3.y, r3.y, c4.z, c4.w
					    sincos r14.y, r3.y
					    mul r3.y, r14.y, c3.w
					    frc r3.y, r3.y
					    mad r1.z, r3.y, -c1.y, r1.z
					    add r3.x, r3.y, r3.x
					    mad r3.x, r3.z, -c1.y, r3.x
					    add r1.zw, r1, r3.z
					    mad r1.y, r1.z, c5.y, r1.y
					    mad r14, v0.xyxy, c1_abs.x, c1_abs.zyyy
					    mad r15, r1.x, c3.x, r14
					    dp2add r1.z, r15, c2, c2.z
					    dp2add r3.y, r15.zwzw, c2, c2.z
					    mad r3.y, r3.y, c4.x, c4.y
					    frc r3.y, r3.y
					    mad r3.y, r3.y, c4.z, c4.w
					    sincos r15.y, r3.y
					    mul r3.y, r15.y, c3.w
					    frc r3.y, r3.y
					    mad r1.z, r1.z, c4.x, c4.y
					    frc r1.z, r1.z
					    mad r1.z, r1.z, c4.z, c4.w
					    sincos r15.y, r1.z
					    mul r1.z, r15.y, c3.w
					    frc r1.z, r1.z
					    add r3.x, r1.z, r3.x
					    mad r1.z, r1.z, -c1.y, r1.w
					    add r1.z, r3.y, r1.z
					    mad r1.y, r3.x, c5.x, r1.y
					    mad r1.y, r1.z, c5.y, r1.y
					    mul oC0.x, r1.y, c5.w
					    mad r3, r1.x, c3.y, r0
					    mad r0, r1.x, c3.z, r0
					    dp2add r1.y, r3, c2, c2.z
					    dp2add r1.z, r3.zwzw, c2, c2.z
					    mad r1.z, r1.z, c4.x, c4.y
					    frc r1.z, r1.z
					    mad r1.z, r1.z, c4.z, c4.w
					    sincos r3.y, r1.z
					    mul r1.z, r3.y, c3.w
					    mad r1.y, r1.y, c4.x, c4.y
					    frc r1.yz, r1
					    mad r1.y, r1.y, c4.z, c4.w
					    sincos r3.y, r1.y
					    mul r1.y, r3.y, c3.w
					    mad r3, r1.x, c3.y, r2
					    mad r2, r1.x, c3.z, r2
					    dp2add r1.w, r3, c2, c2.z
					    dp2add r3.x, r3.zwzw, c2, c2.z
					    mad r3.x, r3.x, c4.x, c4.y
					    frc r3.x, r3.x
					    mad r3.x, r3.x, c4.z, c4.w
					    sincos r15.y, r3.x
					    mul r3.x, r15.y, c3.w
					    frc r3.x, r3.x
					    mad r1.w, r1.w, c4.x, c4.y
					    frc r1.yw, r1
					    mad r1.w, r1.w, c4.z, c4.w
					    sincos r15.y, r1.w
					    mul r1.w, r15.y, c3.w
					    frc r1.w, r1.w
					    mad r1.y, r1.w, -c1.y, r1.y
					    mad r1.w, r3.x, -c1.y, r1.w
					    add r1.y, r3.x, r1.y
					    mad r15, r1.x, c3.y, r4
					    mad r4, r1.x, c3.z, r4
					    dp2add r3.y, r15, c2, c2.z
					    dp2add r3.z, r15.zwzw, c2, c2.z
					    mad r3.z, r3.z, c4.x, c4.y
					    frc r3.z, r3.z
					    mad r3.z, r3.z, c4.z, c4.w
					    sincos r15.y, r3.z
					    mul r3.z, r15.y, c3.w
					    mad r3.y, r3.y, c4.x, c4.y
					    frc r3.yz, r3
					    mad r3.y, r3.y, c4.z, c4.w
					    sincos r15.y, r3.y
					    mul r3.y, r15.y, c3.w
					    frc r3.y, r3.y
					    mad r1.y, r3.y, -c1.y, r1.y
					    mad r3.y, r1.z, -c1.y, r3.y
					    add r3.y, r3.z, r3.y
					    mad r1.y, r1.z, c2.w, r1.y
					    mad r1.y, r3.z, -c1.y, r1.y
					    mad r15, r1.x, c3.y, r5
					    mad r5, r1.x, c3.z, r5
					    dp2add r3.w, r15, c2, c2.z
					    dp2add r6.x, r15.zwzw, c2, c2.z
					    mad r6.x, r6.x, c4.x, c4.y
					    frc r6.x, r6.x
					    mad r6.x, r6.x, c4.z, c4.w
					    sincos r15.y, r6.x
					    mul r6.x, r15.y, c3.w
					    frc r6.x, r6.x
					    mad r3.w, r3.w, c4.x, c4.y
					    frc r3.w, r3.w
					    mad r3.w, r3.w, c4.z, c4.w
					    sincos r15.y, r3.w
					    mul r3.w, r15.y, c3.w
					    frc r3.w, r3.w
					    add r1.y, r1.y, r3.w
					    mad r1.y, r6.x, -c1.y, r1.y
					    mad r15, r1.x, c3.y, r7
					    mad r7, r1.x, c3.z, r7
					    dp2add r6.z, r15, c2, c2.z
					    dp2add r15.x, r15.zwzw, c2, c2.z
					    mad r15.x, r15.x, c4.x, c4.y
					    frc r15.x, r15.x
					    mad r15.x, r15.x, c4.z, c4.w
					    sincos r16.y, r15.x
					    mul r15.x, r16.y, c3.w
					    frc r15.x, r15.x
					    mad r6.z, r6.z, c4.x, c4.y
					    frc r6.z, r6.z
					    mad r6.z, r6.z, c4.z, c4.w
					    sincos r16.y, r6.z
					    mul r6.z, r16.y, c3.w
					    frc r6.z, r6.z
					    add r1.yw, r1, r6.xwzz
					    mad r3.x, r6.z, -c1.y, r3.x
					    mad r1.w, r1.z, -c1.y, r1.w
					    mad r1.z, r3.z, -c1.y, r1.z
					    add r1.z, r15.x, r1.z
					    mad r1.z, r6.x, -c1.y, r1.z
					    mad r1.z, r6.w, c2.w, r1.z
					    mad r1.w, r3.z, c2.w, r1.w
					    mad r1.w, r15.x, -c1.y, r1.w
					    add r1.w, r6.x, r1.w
					    mad r1.w, r6.w, -c1.y, r1.w
					    mad r16, r1.x, c3.y, r9
					    mad r9, r1.x, c3.z, r9
					    dp2add r6.z, r16, c2, c2.z
					    dp2add r15.y, r16.zwzw, c2, c2.z
					    mad r15.y, r15.y, c4.x, c4.y
					    frc r15.y, r15.y
					    mad r15.y, r15.y, c4.z, c4.w
					    sincos r16.y, r15.y
					    mul r15.y, r16.y, c3.w
					    frc r15.y, r15.y
					    add r3.x, r3.x, r15.y
					    mad r3.x, r3.z, -c1.y, r3.x
					    mad r3.z, r15.x, -c1.y, r3.z
					    mad r3.x, r15.x, c2.w, r3.x
					    mad r6.z, r6.z, c4.x, c4.y
					    frc r6.z, r6.z
					    mad r6.z, r6.z, c4.z, c4.w
					    sincos r15.y, r6.z
					    mul r6.z, r15.y, c3.w
					    frc r6.z, r6.z
					    add r1.w, r1.w, r6.z
					    mul r1.w, r1.w, c5.x
					    mad r1.y, r1.y, c5.y, r1.w
					    mad r15, r1.x, c3.y, r10
					    mad r10, r1.x, c3.z, r10
					    dp2add r1.w, r15, c2, c2.z
					    dp2add r15.x, r15.zwzw, c2, c2.z
					    mad r15.x, r15.x, c4.x, c4.y
					    frc r15.x, r15.x
					    mad r15.x, r15.x, c4.z, c4.w
					    sincos r16.y, r15.x
					    mul r15.x, r16.y, c3.w
					    frc r15.x, r15.x
					    mad r1.w, r1.w, c4.x, c4.y
					    frc r1.w, r1.w
					    mad r1.w, r1.w, c4.z, c4.w
					    sincos r16.y, r1.w
					    mul r1.w, r16.y, c3.w
					    frc r1.w, r1.w
					    mad r3.x, r1.w, -c1.y, r3.x
					    add r1.w, r1.w, r3.z
					    mad r1.w, r6.w, -c1.y, r1.w
					    mad r1.w, r6.z, c2.w, r1.w
					    mad r1.w, r15.x, -c1.y, r1.w
					    add r3.x, r6.w, r3.x
					    mad r3.x, r6.z, -c1.y, r3.x
					    add r3.x, r15.x, r3.x
					    mad r1.y, r3.x, c5.y, r1.y
					    mad r3.x, r3.w, -c1.y, r3.y
					    mad r3.y, r6.x, -c1.y, r3.w
					    mad r3.x, r6.x, c2.w, r3.x
					    mad r3.z, r6.w, -c1.y, r6.x
					    add r3.yz, r6.xwzw, r3
					    mad r3.x, r6.w, -c1.y, r3.x
					    mad r3.w, r6.z, -c1.y, r6.w
					    mad r1.z, r6.z, -c1.y, r1.z
					    add r3.w, r15.x, r3.w
					    mad r15, r1.x, c3.y, r8
					    mad r8, r1.x, c3.z, r8
					    dp2add r6.x, r15, c2, c2.z
					    dp2add r6.z, r15.zwzw, c2, c2.z
					    mad r6.z, r6.z, c4.x, c4.y
					    frc r6.z, r6.z
					    mad r6.z, r6.z, c4.z, c4.w
					    sincos r15.y, r6.z
					    mul r6.z, r15.y, c3.w
					    mad r6.x, r6.x, c4.x, c4.y
					    frc r6.xz, r6
					    mad r6.x, r6.x, c4.z, c4.w
					    sincos r15.y, r6.x
					    mul r6.x, r15.y, c3.w
					    frc r6.x, r6.x
					    add r3.x, r3.x, r6.x
					    mad r3.y, r6.x, -c1.y, r3.y
					    mad r3.y, r6.z, c2.w, r3.y
					    mad r3.x, r6.z, -c1.y, r3.x
					    mad r15, r1.x, c3.y, r11
					    mad r11, r1.x, c3.z, r11
					    dp2add r6.x, r15, c2, c2.z
					    dp2add r6.w, r15.zwzw, c2, c2.z
					    mad r6.w, r6.w, c4.x, c4.y
					    frc r6.w, r6.w
					    mad r6.w, r6.w, c4.z, c4.w
					    sincos r15.y, r6.w
					    mul r6.w, r15.y, c3.w
					    mad r6.x, r6.x, c4.x, c4.y
					    frc r6.xw, r6
					    mad r6.x, r6.x, c4.z, c4.w
					    sincos r15.y, r6.x
					    mul r6.x, r15.y, c3.w
					    frc r6.x, r6.x
					    add r3.x, r3.x, r6.x
					    mad r1.y, r3.x, c5.x, r1.y
					    add r1.z, r1.z, r6.z
					    mad r3.x, r6.z, -c1.y, r3.z
					    mad r3.x, r6.x, c2.w, r3.x
					    mad r3.x, r6.w, -c1.y, r3.x
					    mad r1.z, r6.x, -c1.y, r1.z
					    add r1.z, r6.w, r1.z
					    mad r1.y, r1.z, c5.z, r1.y
					    add r1.z, r1.w, r6.x
					    mad r1.z, r6.w, -c1.y, r1.z
					    mad r15, r1.x, c3.y, r13
					    mad r13, r1.x, c3.z, r13
					    dp2add r1.w, r15, c2, c2.z
					    dp2add r3.z, r15.zwzw, c2, c2.z
					    mad r3.z, r3.z, c4.x, c4.y
					    frc r3.z, r3.z
					    mad r3.z, r3.z, c4.z, c4.w
					    sincos r15.y, r3.z
					    mul r3.z, r15.y, c3.w
					    frc r3.z, r3.z
					    mad r1.w, r1.w, c4.x, c4.y
					    frc r1.w, r1.w
					    mad r1.w, r1.w, c4.z, c4.w
					    sincos r15.y, r1.w
					    mul r1.w, r15.y, c3.w
					    frc r1.w, r1.w
					    add r1.z, r1.w, r1.z
					    mad r1.y, r1.z, c5.x, r1.y
					    mad r1.z, r6.x, -c1.y, r3.y
					    mad r3.y, r6.x, -c1.y, r3.w
					    mad r3.y, r6.w, c2.w, r3.y
					    mad r1.w, r1.w, -c1.y, r3.y
					    add r1.z, r3.z, r1.z
					    mad r15, r1.x, c3.y, r12
					    mad r12, r1.x, c3.z, r12
					    dp2add r3.y, r15, c2, c2.z
					    dp2add r3.z, r15.zwzw, c2, c2.z
					    mad r3.z, r3.z, c4.x, c4.y
					    frc r3.z, r3.z
					    mad r3.z, r3.z, c4.z, c4.w
					    sincos r15.y, r3.z
					    mul r3.z, r15.y, c3.w
					    mad r3.y, r3.y, c4.x, c4.y
					    frc r3.yz, r3
					    mad r3.y, r3.y, c4.z, c4.w
					    sincos r15.y, r3.y
					    mul r3.y, r15.y, c3.w
					    frc r3.y, r3.y
					    mad r1.z, r3.y, -c1.y, r1.z
					    add r3.x, r3.y, r3.x
					    mad r3.x, r3.z, -c1.y, r3.x
					    add r1.zw, r1, r3.z
					    mad r1.y, r1.z, c5.y, r1.y
					    mad r15, r1.x, c3.y, r14
					    mad r14, r1.x, c3.z, r14
					    dp2add r1.x, r15, c2, c2.z
					    dp2add r1.z, r15.zwzw, c2, c2.z
					    mad r1.z, r1.z, c4.x, c4.y
					    frc r1.z, r1.z
					    mad r1.z, r1.z, c4.z, c4.w
					    sincos r15.y, r1.z
					    mul r1.z, r15.y, c3.w
					    mad r1.x, r1.x, c4.x, c4.y
					    frc r1.xz, r1
					    mad r1.x, r1.x, c4.z, c4.w
					    sincos r15.y, r1.x
					    mul r1.x, r15.y, c3.w
					    frc r1.x, r1.x
					    add r3.x, r1.x, r3.x
					    mad r1.x, r1.x, -c1.y, r1.w
					    add r1.x, r1.z, r1.x
					    mad r1.y, r3.x, c5.x, r1.y
					    mad r1.x, r1.x, c5.y, r1.y
					    mul oC0.y, r1.x, c5.w
					    dp2add r0.x, r0, c2, c2.z
					    dp2add r0.y, r0.zwzw, c2, c2.z
					    mad r0.y, r0.y, c4.x, c4.y
					    frc r0.y, r0.y
					    mad r0.y, r0.y, c4.z, c4.w
					    sincos r1.y, r0.y
					    mul r0.y, r1.y, c3.w
					    mad r0.x, r0.x, c4.x, c4.y
					    frc r0.xy, r0
					    mad r0.x, r0.x, c4.z, c4.w
					    sincos r1.y, r0.x
					    mul r0.x, r1.y, c3.w
					    dp2add r0.z, r2, c2, c2.z
					    dp2add r0.w, r2.zwzw, c2, c2.z
					    mad r0.w, r0.w, c4.x, c4.y
					    frc r0.xw, r0
					    mad r0.w, r0.w, c4.z, c4.w
					    sincos r1.y, r0.w
					    mul r0.w, r1.y, c3.w
					    mad r0.z, r0.z, c4.x, c4.y
					    frc r0.zw, r0
					    mad r0.z, r0.z, c4.z, c4.w
					    sincos r1.y, r0.z
					    mul r0.z, r1.y, c3.w
					    frc r0.z, r0.z
					    mad r0.x, r0.z, -c1.y, r0.x
					    mad r0.z, r0.w, -c1.y, r0.z
					    add r0.x, r0.w, r0.x
					    dp2add r1.x, r4, c2, c2.z
					    dp2add r1.y, r4.zwzw, c2, c2.z
					    mad r1.y, r1.y, c4.x, c4.y
					    frc r1.y, r1.y
					    mad r1.y, r1.y, c4.z, c4.w
					    sincos r2.y, r1.y
					    mul r1.y, r2.y, c3.w
					    mad r1.x, r1.x, c4.x, c4.y
					    frc r1.xy, r1
					    mad r1.x, r1.x, c4.z, c4.w
					    sincos r2.y, r1.x
					    mul r1.x, r2.y, c3.w
					    frc r1.x, r1.x
					    mad r0.x, r1.x, -c1.y, r0.x
					    mad r1.x, r0.y, -c1.y, r1.x
					    add r1.x, r1.y, r1.x
					    mad r0.x, r0.y, c2.w, r0.x
					    mad r0.x, r1.y, -c1.y, r0.x
					    dp2add r1.z, r5, c2, c2.z
					    dp2add r1.w, r5.zwzw, c2, c2.z
					    mad r1.w, r1.w, c4.x, c4.y
					    frc r1.w, r1.w
					    mad r1.w, r1.w, c4.z, c4.w
					    sincos r2.y, r1.w
					    mul r1.w, r2.y, c3.w
					    mad r1.z, r1.z, c4.x, c4.y
					    frc r1.zw, r1
					    mad r1.z, r1.z, c4.z, c4.w
					    sincos r2.y, r1.z
					    mul r1.z, r2.y, c3.w
					    frc r1.z, r1.z
					    add r0.x, r0.x, r1.z
					    mad r0.x, r1.w, -c1.y, r0.x
					    add r0.x, r6.y, r0.x
					    dp2add r2.x, r7, c2, c2.z
					    dp2add r2.y, r7.zwzw, c2, c2.z
					    mad r2.y, r2.y, c4.x, c4.y
					    frc r2.y, r2.y
					    mad r2.y, r2.y, c4.z, c4.w
					    sincos r3.y, r2.y
					    mul r2.y, r3.y, c3.w
					    mad r2.x, r2.x, c4.x, c4.y
					    frc r2.xy, r2
					    mad r2.x, r2.x, c4.z, c4.w
					    sincos r3.y, r2.x
					    mul r2.x, r3.y, c3.w
					    frc r2.x, r2.x
					    add r0.z, r0.z, r2.x
					    mad r0.w, r2.x, -c1.y, r0.w
					    mad r0.z, r0.y, -c1.y, r0.z
					    mad r0.y, r1.y, -c1.y, r0.y
					    add r0.y, r2.y, r0.y
					    mad r0.y, r1.w, -c1.y, r0.y
					    mad r0.y, r6.y, c2.w, r0.y
					    mad r0.z, r1.y, c2.w, r0.z
					    mad r0.z, r2.y, -c1.y, r0.z
					    add r0.z, r1.w, r0.z
					    mad r0.z, r6.y, -c1.y, r0.z
					    dp2add r2.x, r9, c2, c2.z
					    dp2add r2.z, r9.zwzw, c2, c2.z
					    mad r2.z, r2.z, c4.x, c4.y
					    frc r2.z, r2.z
					    mad r2.z, r2.z, c4.z, c4.w
					    sincos r3.y, r2.z
					    mul r2.z, r3.y, c3.w
					    frc r2.z, r2.z
					    add r0.w, r0.w, r2.z
					    mad r0.w, r1.y, -c1.y, r0.w
					    mad r1.y, r2.y, -c1.y, r1.y
					    mad r0.w, r2.y, c2.w, r0.w
					    mad r2.x, r2.x, c4.x, c4.y
					    frc r2.x, r2.x
					    mad r2.x, r2.x, c4.z, c4.w
					    sincos r3.y, r2.x
					    mul r2.x, r3.y, c3.w
					    frc r2.x, r2.x
					    add r0.z, r0.z, r2.x
					    mul r0.z, r0.z, c5.x
					    mad r0.x, r0.x, c5.y, r0.z
					    dp2add r0.z, r10, c2, c2.z
					    dp2add r2.y, r10.zwzw, c2, c2.z
					    mad r2.y, r2.y, c4.x, c4.y
					    frc r2.y, r2.y
					    mad r2.y, r2.y, c4.z, c4.w
					    sincos r3.y, r2.y
					    mul r2.y, r3.y, c3.w
					    frc r2.y, r2.y
					    mad r0.z, r0.z, c4.x, c4.y
					    frc r0.z, r0.z
					    mad r0.z, r0.z, c4.z, c4.w
					    sincos r3.y, r0.z
					    mul r0.z, r3.y, c3.w
					    frc r0.z, r0.z
					    mad r0.w, r0.z, -c1.y, r0.w
					    add r0.z, r0.z, r1.y
					    mad r0.z, r6.y, -c1.y, r0.z
					    mad r0.z, r2.x, c2.w, r0.z
					    mad r0.z, r2.y, -c1.y, r0.z
					    add r0.w, r6.y, r0.w
					    mad r0.w, r2.x, -c1.y, r0.w
					    add r0.w, r2.y, r0.w
					    mad r0.x, r0.w, c5.y, r0.x
					    mad r0.w, r1.z, -c1.y, r1.x
					    mad r1.x, r1.w, -c1.y, r1.z
					    add r1.x, r6.y, r1.x
					    mad r0.w, r1.w, c2.w, r0.w
					    mad r1.y, r6.y, -c1.y, r1.w
					    mad r0.w, r6.y, -c1.y, r0.w
					    mad r1.z, r2.x, -c1.y, r6.y
					    mad r0.y, r2.x, -c1.y, r0.y
					    add r1.yz, r2.xxyw, r1
					    dp2add r1.w, r8, c2, c2.z
					    dp2add r2.x, r8.zwzw, c2, c2.z
					    mad r2.x, r2.x, c4.x, c4.y
					    frc r2.x, r2.x
					    mad r2.x, r2.x, c4.z, c4.w
					    sincos r3.y, r2.x
					    mul r2.x, r3.y, c3.w
					    frc r2.x, r2.x
					    mad r1.w, r1.w, c4.x, c4.y
					    frc r1.w, r1.w
					    mad r1.w, r1.w, c4.z, c4.w
					    sincos r3.y, r1.w
					    mul r1.w, r3.y, c3.w
					    frc r1.w, r1.w
					    add r0.w, r0.w, r1.w
					    mad r1.x, r1.w, -c1.y, r1.x
					    mad r1.x, r2.x, c2.w, r1.x
					    mad r0.w, r2.x, -c1.y, r0.w
					    dp2add r1.w, r11, c2, c2.z
					    dp2add r2.y, r11.zwzw, c2, c2.z
					    mad r2.y, r2.y, c4.x, c4.y
					    frc r2.y, r2.y
					    mad r2.y, r2.y, c4.z, c4.w
					    sincos r3.y, r2.y
					    mul r2.y, r3.y, c3.w
					    frc r2.y, r2.y
					    mad r1.w, r1.w, c4.x, c4.y
					    frc r1.w, r1.w
					    mad r1.w, r1.w, c4.z, c4.w
					    sincos r3.y, r1.w
					    mul r1.w, r3.y, c3.w
					    frc r1.w, r1.w
					    add r0.w, r0.w, r1.w
					    mad r0.x, r0.w, c5.x, r0.x
					    add r0.y, r0.y, r2.x
					    mad r0.w, r2.x, -c1.y, r1.y
					    mad r0.w, r1.w, c2.w, r0.w
					    mad r0.w, r2.y, -c1.y, r0.w
					    mad r0.y, r1.w, -c1.y, r0.y
					    add r0.y, r2.y, r0.y
					    mad r0.x, r0.y, c5.z, r0.x
					    add r0.y, r0.z, r1.w
					    mad r0.y, r2.y, -c1.y, r0.y
					    dp2add r0.z, r13, c2, c2.z
					    dp2add r1.y, r13.zwzw, c2, c2.z
					    mad r1.y, r1.y, c4.x, c4.y
					    frc r1.y, r1.y
					    mad r1.y, r1.y, c4.z, c4.w
					    sincos r3.y, r1.y
					    mul r1.y, r3.y, c3.w
					    frc r1.y, r1.y
					    mad r0.z, r0.z, c4.x, c4.y
					    frc r0.z, r0.z
					    mad r0.z, r0.z, c4.z, c4.w
					    sincos r3.y, r0.z
					    mul r0.z, r3.y, c3.w
					    frc r0.z, r0.z
					    add r0.y, r0.z, r0.y
					    mad r0.x, r0.y, c5.x, r0.x
					    mad r0.y, r1.w, -c1.y, r1.x
					    mad r1.x, r1.w, -c1.y, r1.z
					    mad r1.x, r2.y, c2.w, r1.x
					    mad r0.z, r0.z, -c1.y, r1.x
					    add r0.y, r1.y, r0.y
					    dp2add r1.x, r12, c2, c2.z
					    dp2add r1.y, r12.zwzw, c2, c2.z
					    mad r1.y, r1.y, c4.x, c4.y
					    frc r1.y, r1.y
					    mad r1.y, r1.y, c4.z, c4.w
					    sincos r2.y, r1.y
					    mul r1.y, r2.y, c3.w
					    mad r1.x, r1.x, c4.x, c4.y
					    frc r1.xy, r1
					    mad r1.x, r1.x, c4.z, c4.w
					    sincos r2.y, r1.x
					    mul r1.x, r2.y, c3.w
					    frc r1.x, r1.x
					    mad r0.y, r1.x, -c1.y, r0.y
					    add r0.yzw, r0, r1.xyyx
					    mad r0.w, r1.y, -c1.y, r0.w
					    mad r0.x, r0.y, c5.y, r0.x
					    dp2add r0.y, r14, c2, c2.z
					    dp2add r1.x, r14.zwzw, c2, c2.z
					    mad r1.x, r1.x, c4.x, c4.y
					    frc r1.x, r1.x
					    mad r1.x, r1.x, c4.z, c4.w
					    sincos r2.y, r1.x
					    mul r1.x, r2.y, c3.w
					    frc r1.x, r1.x
					    mad r0.y, r0.y, c4.x, c4.y
					    frc r0.y, r0.y
					    mad r0.y, r0.y, c4.z, c4.w
					    sincos r2.y, r0.y
					    mul r0.y, r2.y, c3.w
					    frc r0.y, r0.y
					    add r0.w, r0.y, r0.w
					    mad r0.y, r0.y, -c1.y, r0.z
					    add r0.y, r1.x, r0.y
					    mad r0.x, r0.w, c5.x, r0.x
					    mad r0.x, r0.y, c5.y, r0.x
					    mul oC0.z, r0.x, c5.w
					    mov oC0.w, -c1.z
					
					// approximately 1394 instruction slots used"
				}
				SubProgram "d3d11 " {
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1     zw        1     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 17
					mad r0.xyzw, v1.xyxy, l(192.000000, 192.000000, 192.000000, 192.000000), l(-2.000000, -2.000000, -1.000000, -1.000000)
					frc r1.x, cb0[4].x
					mad r2.xyzw, r1.xxxx, l(0.130000, 0.130000, 0.130000, 0.130000), r0.xyzw
					dp2 r1.y, r2.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r1.z, r2.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r1.yz, null, r1.yyzy
					mul r1.yz, r1.yyzy, l(0.000000, 43758.546875, 43758.546875, 0.000000)
					mad r2.xyzw, v1.xyxy, l(192.000000, 192.000000, 192.000000, 192.000000), l(-1.000000, -2.000000, 0.000000, -2.000000)
					mad r3.xyzw, r1.xxxx, l(0.130000, 0.130000, 0.130000, 0.130000), r2.xyzw
					dp2 r1.w, r3.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r3.x, r3.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r3.x, null, r3.x
					mul r3.x, r3.x, l(43758.546875)
					frc r3.x, r3.x
					sincos r1.w, null, r1.w
					mul r1.w, r1.w, l(43758.546875)
					frc r1.yzw, r1.yyzw
					mad r1.y, r1.w, l(2.000000), r1.y
					mad r1.w, r3.x, l(2.000000), r1.w
					add r1.y, r3.x, r1.y
					mad r4.xyzw, v1.xyxy, l(192.000000, 192.000000, 192.000000, 192.000000), l(-2.000000, -1.000000, 0.000000, -1.000000)
					mad r5.xyzw, r1.xxxx, l(0.130000, 0.130000, 0.130000, 0.130000), r4.xyzw
					dp2 r3.y, r5.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r3.z, r5.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r3.yz, null, r3.yyzy
					mul r3.yz, r3.yyzy, l(0.000000, 43758.546875, 43758.546875, 0.000000)
					frc r3.yz, r3.yyzy
					mad r1.y, r3.y, l(2.000000), r1.y
					mad r3.y, r1.z, l(2.000000), r3.y
					add r3.y, r3.z, r3.y
					mad r1.y, r1.z, l(-12.000000), r1.y
					mad r1.y, r3.z, l(2.000000), r1.y
					mad r5.xyzw, v1.xyxy, l(192.000000, 192.000000, 192.000000, 192.000000), l(-2.000000, 0.000000, -1.000000, 0.000000)
					mad r6.xyzw, r1.xxxx, l(0.130000, 0.130000, 0.130000, 0.130000), r5.xyzw
					dp2 r3.w, r6.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r6.x, r6.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r6.x, null, r6.x
					mul r6.x, r6.x, l(43758.546875)
					frc r6.x, r6.x
					sincos r3.w, null, r3.w
					mul r3.w, r3.w, l(43758.546875)
					frc r3.w, r3.w
					add r1.y, r1.y, r3.w
					mad r1.y, r6.x, l(2.000000), r1.y
					mul r6.yzw, r1.xxxx, l(0.000000, 0.070000, 0.110000, 0.130000)
					mad r7.xy, v1.xyxx, l(192.000000, 192.000000, 0.000000, 0.000000), r6.wwww
					mad r8.xyzw, v1.xyxy, l(192.000000, 192.000000, 192.000000, 192.000000), r6.yyzz
					dp2 r6.y, r7.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r6.y, null, r6.y
					mul r6.y, r6.y, l(43758.546875)
					frc r6.y, r6.y
					mad r7.xyzw, v1.xyxy, l(192.000000, 192.000000, 192.000000, 192.000000), l(1.000000, -2.000000, 1.000000, -1.000000)
					mad r9.xyzw, r1.xxxx, l(0.130000, 0.130000, 0.130000, 0.130000), r7.xyzw
					dp2 r6.z, r9.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r6.w, r9.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r6.zw, null, r6.zzzw
					mul r6.zw, r6.zzzw, l(0.000000, 0.000000, 43758.546875, 43758.546875)
					frc r6.zw, r6.zzzw
					add r1.yw, r1.yyyw, r6.yyyz
					mad r3.x, r6.z, l(2.000000), r3.x
					mad r1.w, r1.z, l(2.000000), r1.w
					mad r1.z, r3.z, l(2.000000), r1.z
					add r1.z, r6.w, r1.z
					mad r1.z, r6.x, l(2.000000), r1.z
					mad r1.z, r6.y, l(-12.000000), r1.z
					mad r1.w, r3.z, l(-12.000000), r1.w
					mad r1.w, r6.w, l(2.000000), r1.w
					add r1.w, r6.x, r1.w
					mad r1.w, r6.y, l(2.000000), r1.w
					mad r9.xyzw, v1.xyxy, l(192.000000, 192.000000, 192.000000, 192.000000), l(1.000000, 0.000000, 2.000000, -2.000000)
					mad r10.xyzw, r1.xxxx, l(0.130000, 0.130000, 0.130000, 0.130000), r9.xyzw
					dp2 r6.z, r10.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r10.x, r10.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r10.x, null, r10.x
					mul r10.x, r10.x, l(43758.546875)
					frc r10.x, r10.x
					add r3.x, r3.x, r10.x
					mad r3.x, r3.z, l(2.000000), r3.x
					mad r3.z, r6.w, l(2.000000), r3.z
					mad r3.x, r6.w, l(-12.000000), r3.x
					sincos r6.z, null, r6.z
					mul r6.z, r6.z, l(43758.546875)
					frc r6.z, r6.z
					add r1.w, r1.w, r6.z
					mul r1.w, r1.w, l(0.083333)
					mad r1.y, r1.y, l(0.041667), r1.w
					mad r10.xyzw, v1.xyxy, l(192.000000, 192.000000, 192.000000, 192.000000), l(2.000000, -1.000000, 2.000000, 0.000000)
					mad r11.xyzw, r1.xxxx, l(0.130000, 0.130000, 0.130000, 0.130000), r10.xyzw
					dp2 r1.w, r11.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r6.w, r11.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r6.w, null, r6.w
					mul r6.w, r6.w, l(43758.546875)
					frc r6.w, r6.w
					sincos r1.w, null, r1.w
					mul r1.w, r1.w, l(43758.546875)
					frc r1.w, r1.w
					mad r3.x, r1.w, l(2.000000), r3.x
					add r1.w, r1.w, r3.z
					mad r1.w, r6.y, l(2.000000), r1.w
					mad r1.w, r6.z, l(-12.000000), r1.w
					mad r1.w, r6.w, l(2.000000), r1.w
					add r3.x, r6.y, r3.x
					mad r3.x, r6.z, l(2.000000), r3.x
					add r3.x, r6.w, r3.x
					mad r1.y, r3.x, l(0.041667), r1.y
					mad r3.x, r3.w, l(2.000000), r3.y
					mad r3.y, r6.x, l(2.000000), r3.w
					mad r3.x, r6.x, l(-12.000000), r3.x
					mad r3.z, r6.y, l(2.000000), r6.x
					mad r3.x, r6.y, l(2.000000), r3.x
					mad r3.w, r6.z, l(2.000000), r6.y
					mad r1.z, r6.z, l(2.000000), r1.z
					add r3.yzw, r6.yyzw, r3.yyzw
					mad r6.xyzw, v1.xyxy, l(192.000000, 192.000000, 192.000000, 192.000000), l(-2.000000, 1.000000, -1.000000, 1.000000)
					mad r11.xyzw, r1.xxxx, l(0.130000, 0.130000, 0.130000, 0.130000), r6.xyzw
					dp2 r11.x, r11.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r11.y, r11.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r11.xy, null, r11.xyxx
					mul r11.xy, r11.xyxx, l(43758.546875, 43758.546875, 0.000000, 0.000000)
					frc r11.xy, r11.xyxx
					add r3.x, r3.x, r11.x
					mad r3.y, r11.x, l(2.000000), r3.y
					mad r3.y, r11.y, l(-12.000000), r3.y
					mad r3.x, r11.y, l(2.000000), r3.x
					mad r12.xyzw, v1.xyxy, l(192.000000, 192.000000, 192.000000, 192.000000), l(0.000000, 1.000000, 1.000000, 1.000000)
					mad r13.xyzw, r1.xxxx, l(0.130000, 0.130000, 0.130000, 0.130000), r12.xyzw
					dp2 r11.x, r13.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r11.z, r13.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r11.xz, null, r11.xxzx
					mul r11.xz, r11.xxzx, l(43758.546875, 0.000000, 43758.546875, 0.000000)
					frc r11.xz, r11.xxzx
					add r3.x, r3.x, r11.x
					mad r1.y, r3.x, l(0.083333), r1.y
					add r1.z, r1.z, r11.y
					mad r3.x, r11.y, l(2.000000), r3.z
					mad r3.x, r11.x, l(-12.000000), r3.x
					mad r3.x, r11.z, l(2.000000), r3.x
					mad r1.z, r11.x, l(2.000000), r1.z
					add r1.z, r11.z, r1.z
					mad r1.y, r1.z, l(0.166667), r1.y
					add r1.z, r1.w, r11.x
					mad r1.z, r11.z, l(2.000000), r1.z
					mad r13.xyzw, v1.xyxy, l(192.000000, 192.000000, 192.000000, 192.000000), l(2.000000, 1.000000, -2.000000, 2.000000)
					mad r14.xyzw, r1.xxxx, l(0.130000, 0.130000, 0.130000, 0.130000), r13.xyzw
					dp2 r1.w, r14.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r3.z, r14.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r3.z, null, r3.z
					mul r3.z, r3.z, l(43758.546875)
					frc r3.z, r3.z
					sincos r1.w, null, r1.w
					mul r1.w, r1.w, l(43758.546875)
					frc r1.w, r1.w
					add r1.z, r1.w, r1.z
					mad r1.y, r1.z, l(0.083333), r1.y
					mad r1.z, r11.x, l(2.000000), r3.y
					mad r3.y, r11.x, l(2.000000), r3.w
					mad r3.y, r11.z, l(-12.000000), r3.y
					mad r1.w, r1.w, l(2.000000), r3.y
					add r1.z, r3.z, r1.z
					mad r11.xyzw, v1.xyxy, l(192.000000, 192.000000, 192.000000, 192.000000), l(-1.000000, 2.000000, 0.000000, 2.000000)
					mad r14.xyzw, r1.xxxx, l(0.130000, 0.130000, 0.130000, 0.130000), r11.xyzw
					dp2 r3.y, r14.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r3.z, r14.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r3.yz, null, r3.yyzy
					mul r3.yz, r3.yyzy, l(0.000000, 43758.546875, 43758.546875, 0.000000)
					frc r3.yz, r3.yyzy
					mad r1.z, r3.y, l(2.000000), r1.z
					add r3.x, r3.y, r3.x
					mad r3.x, r3.z, l(2.000000), r3.x
					add r1.zw, r1.zzzw, r3.zzzz
					mad r1.y, r1.z, l(0.041667), r1.y
					mad r14.xyzw, v1.xyxy, l(192.000000, 192.000000, 192.000000, 192.000000), l(1.000000, 2.000000, 2.000000, 2.000000)
					mad r15.xyzw, r1.xxxx, l(0.130000, 0.130000, 0.130000, 0.130000), r14.xyzw
					dp2 r1.z, r15.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r3.y, r15.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r3.y, null, r3.y
					mul r3.y, r3.y, l(43758.546875)
					frc r3.y, r3.y
					sincos r1.z, null, r1.z
					mul r1.z, r1.z, l(43758.546875)
					frc r1.z, r1.z
					add r3.x, r1.z, r3.x
					mad r1.z, r1.z, l(2.000000), r1.w
					add r1.z, r3.y, r1.z
					mad r1.y, r3.x, l(0.083333), r1.y
					mad r1.y, r1.z, l(0.041667), r1.y
					mul o0.z, r1.y, l(0.062500)
					mad r3.xyzw, r1.xxxx, l(0.070000, 0.070000, 0.070000, 0.070000), r0.xyzw
					mad r0.xyzw, r1.xxxx, l(0.110000, 0.110000, 0.110000, 0.110000), r0.xyzw
					dp2 r1.y, r3.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r1.z, r3.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r1.yz, null, r1.yyzy
					mul r1.yz, r1.yyzy, l(0.000000, 43758.546875, 43758.546875, 0.000000)
					mad r3.xyzw, r1.xxxx, l(0.070000, 0.070000, 0.070000, 0.070000), r2.xyzw
					mad r2.xyzw, r1.xxxx, l(0.110000, 0.110000, 0.110000, 0.110000), r2.xyzw
					dp2 r1.w, r3.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r3.x, r3.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r3.x, null, r3.x
					mul r3.x, r3.x, l(43758.546875)
					frc r3.x, r3.x
					sincos r1.w, null, r1.w
					mul r1.w, r1.w, l(43758.546875)
					frc r1.yzw, r1.yyzw
					mad r1.y, r1.w, l(2.000000), r1.y
					mad r1.w, r3.x, l(2.000000), r1.w
					add r1.y, r3.x, r1.y
					mad r15.xyzw, r1.xxxx, l(0.070000, 0.070000, 0.070000, 0.070000), r4.xyzw
					mad r4.xyzw, r1.xxxx, l(0.110000, 0.110000, 0.110000, 0.110000), r4.xyzw
					dp2 r3.y, r15.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r3.z, r15.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r3.yz, null, r3.yyzy
					mul r3.yz, r3.yyzy, l(0.000000, 43758.546875, 43758.546875, 0.000000)
					frc r3.yz, r3.yyzy
					mad r1.y, r3.y, l(2.000000), r1.y
					mad r3.y, r1.z, l(2.000000), r3.y
					add r3.y, r3.z, r3.y
					mad r1.y, r1.z, l(-12.000000), r1.y
					mad r1.y, r3.z, l(2.000000), r1.y
					mad r15.xyzw, r1.xxxx, l(0.070000, 0.070000, 0.070000, 0.070000), r5.xyzw
					mad r5.xyzw, r1.xxxx, l(0.110000, 0.110000, 0.110000, 0.110000), r5.xyzw
					dp2 r3.w, r15.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r15.x, r15.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r15.x, null, r15.x
					mul r15.x, r15.x, l(43758.546875)
					frc r15.x, r15.x
					sincos r3.w, null, r3.w
					mul r3.w, r3.w, l(43758.546875)
					frc r3.w, r3.w
					add r1.y, r1.y, r3.w
					mad r1.y, r15.x, l(2.000000), r1.y
					dp2 r8.x, r8.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r8.y, r8.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r8.xy, null, r8.xyxx
					mul r8.xy, r8.xyxx, l(43758.546875, 43758.546875, 0.000000, 0.000000)
					frc r8.xy, r8.xyxx
					mad r16.xyzw, r1.xxxx, l(0.070000, 0.070000, 0.070000, 0.070000), r7.xyzw
					mad r7.xyzw, r1.xxxx, l(0.110000, 0.110000, 0.110000, 0.110000), r7.xyzw
					dp2 r8.z, r16.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r8.w, r16.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r8.zw, null, r8.zzzw
					mul r8.zw, r8.zzzw, l(0.000000, 0.000000, 43758.546875, 43758.546875)
					frc r8.zw, r8.zzzw
					add r1.yw, r1.yyyw, r8.xxxz
					mad r3.x, r8.z, l(2.000000), r3.x
					mad r1.w, r1.z, l(2.000000), r1.w
					mad r1.z, r3.z, l(2.000000), r1.z
					add r1.z, r8.w, r1.z
					mad r1.z, r15.x, l(2.000000), r1.z
					mad r1.z, r8.x, l(-12.000000), r1.z
					mad r1.w, r3.z, l(-12.000000), r1.w
					mad r1.w, r8.w, l(2.000000), r1.w
					add r1.w, r15.x, r1.w
					mad r1.w, r8.x, l(2.000000), r1.w
					mad r16.xyzw, r1.xxxx, l(0.070000, 0.070000, 0.070000, 0.070000), r9.xyzw
					mad r9.xyzw, r1.xxxx, l(0.110000, 0.110000, 0.110000, 0.110000), r9.xyzw
					dp2 r8.z, r16.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r15.y, r16.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r15.y, null, r15.y
					mul r15.y, r15.y, l(43758.546875)
					frc r15.y, r15.y
					add r3.x, r3.x, r15.y
					mad r3.x, r3.z, l(2.000000), r3.x
					mad r3.z, r8.w, l(2.000000), r3.z
					mad r3.x, r8.w, l(-12.000000), r3.x
					sincos r8.z, null, r8.z
					mul r8.z, r8.z, l(43758.546875)
					frc r8.z, r8.z
					add r1.w, r1.w, r8.z
					mul r1.w, r1.w, l(0.083333)
					mad r1.y, r1.y, l(0.041667), r1.w
					mad r16.xyzw, r1.xxxx, l(0.070000, 0.070000, 0.070000, 0.070000), r10.xyzw
					mad r10.xyzw, r1.xxxx, l(0.110000, 0.110000, 0.110000, 0.110000), r10.xyzw
					dp2 r1.w, r16.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r8.w, r16.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r8.w, null, r8.w
					mul r8.w, r8.w, l(43758.546875)
					frc r8.w, r8.w
					sincos r1.w, null, r1.w
					mul r1.w, r1.w, l(43758.546875)
					frc r1.w, r1.w
					mad r3.x, r1.w, l(2.000000), r3.x
					add r1.w, r1.w, r3.z
					mad r1.w, r8.x, l(2.000000), r1.w
					mad r1.w, r8.z, l(-12.000000), r1.w
					mad r1.w, r8.w, l(2.000000), r1.w
					add r3.x, r8.x, r3.x
					mad r3.x, r8.z, l(2.000000), r3.x
					add r3.x, r8.w, r3.x
					mad r1.y, r3.x, l(0.041667), r1.y
					mad r3.x, r3.w, l(2.000000), r3.y
					mad r3.y, r15.x, l(2.000000), r3.w
					mad r3.x, r15.x, l(-12.000000), r3.x
					mad r3.z, r8.x, l(2.000000), r15.x
					mad r3.x, r8.x, l(2.000000), r3.x
					mad r3.w, r8.z, l(2.000000), r8.x
					mad r1.z, r8.z, l(2.000000), r1.z
					add r3.yzw, r8.xxzw, r3.yyzw
					mad r15.xyzw, r1.xxxx, l(0.070000, 0.070000, 0.070000, 0.070000), r6.xyzw
					mad r6.xyzw, r1.xxxx, l(0.110000, 0.110000, 0.110000, 0.110000), r6.xyzw
					dp2 r8.x, r15.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r8.z, r15.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r8.xz, null, r8.xxzx
					mul r8.xz, r8.xxzx, l(43758.546875, 0.000000, 43758.546875, 0.000000)
					frc r8.xz, r8.xxzx
					add r3.x, r3.x, r8.x
					mad r3.y, r8.x, l(2.000000), r3.y
					mad r3.y, r8.z, l(-12.000000), r3.y
					mad r3.x, r8.z, l(2.000000), r3.x
					mad r15.xyzw, r1.xxxx, l(0.070000, 0.070000, 0.070000, 0.070000), r12.xyzw
					mad r12.xyzw, r1.xxxx, l(0.110000, 0.110000, 0.110000, 0.110000), r12.xyzw
					dp2 r8.x, r15.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r8.w, r15.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r8.xw, null, r8.xxxw
					mul r8.xw, r8.xxxw, l(43758.546875, 0.000000, 0.000000, 43758.546875)
					frc r8.xw, r8.xxxw
					add r3.x, r3.x, r8.x
					mad r1.y, r3.x, l(0.083333), r1.y
					add r1.z, r1.z, r8.z
					mad r3.x, r8.z, l(2.000000), r3.z
					mad r3.x, r8.x, l(-12.000000), r3.x
					mad r3.x, r8.w, l(2.000000), r3.x
					mad r1.z, r8.x, l(2.000000), r1.z
					add r1.z, r8.w, r1.z
					mad r1.y, r1.z, l(0.166667), r1.y
					add r1.z, r1.w, r8.x
					mad r1.z, r8.w, l(2.000000), r1.z
					mad r15.xyzw, r1.xxxx, l(0.070000, 0.070000, 0.070000, 0.070000), r13.xyzw
					mad r13.xyzw, r1.xxxx, l(0.110000, 0.110000, 0.110000, 0.110000), r13.xyzw
					dp2 r1.w, r15.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r3.z, r15.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r3.z, null, r3.z
					mul r3.z, r3.z, l(43758.546875)
					frc r3.z, r3.z
					sincos r1.w, null, r1.w
					mul r1.w, r1.w, l(43758.546875)
					frc r1.w, r1.w
					add r1.z, r1.w, r1.z
					mad r1.y, r1.z, l(0.083333), r1.y
					mad r1.z, r8.x, l(2.000000), r3.y
					mad r3.y, r8.x, l(2.000000), r3.w
					mad r3.y, r8.w, l(-12.000000), r3.y
					mad r1.w, r1.w, l(2.000000), r3.y
					add r1.z, r3.z, r1.z
					mad r15.xyzw, r1.xxxx, l(0.070000, 0.070000, 0.070000, 0.070000), r11.xyzw
					mad r11.xyzw, r1.xxxx, l(0.110000, 0.110000, 0.110000, 0.110000), r11.xyzw
					dp2 r3.y, r15.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r3.z, r15.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r3.yz, null, r3.yyzy
					mul r3.yz, r3.yyzy, l(0.000000, 43758.546875, 43758.546875, 0.000000)
					frc r3.yz, r3.yyzy
					mad r1.z, r3.y, l(2.000000), r1.z
					add r3.x, r3.y, r3.x
					mad r3.x, r3.z, l(2.000000), r3.x
					add r1.zw, r1.zzzw, r3.zzzz
					mad r1.y, r1.z, l(0.041667), r1.y
					mad r15.xyzw, r1.xxxx, l(0.070000, 0.070000, 0.070000, 0.070000), r14.xyzw
					mad r14.xyzw, r1.xxxx, l(0.110000, 0.110000, 0.110000, 0.110000), r14.xyzw
					dp2 r1.x, r15.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r1.z, r15.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r1.xz, null, r1.xxzx
					mul r1.xz, r1.xxzx, l(43758.546875, 0.000000, 43758.546875, 0.000000)
					frc r1.xz, r1.xxzx
					add r3.x, r1.x, r3.x
					mad r1.x, r1.x, l(2.000000), r1.w
					add r1.x, r1.z, r1.x
					mad r1.y, r3.x, l(0.083333), r1.y
					mad r1.x, r1.x, l(0.041667), r1.y
					mul o0.x, r1.x, l(0.062500)
					dp2 r0.x, r0.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r0.y, r0.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r0.xy, null, r0.xyxx
					mul r0.xy, r0.xyxx, l(43758.546875, 43758.546875, 0.000000, 0.000000)
					dp2 r0.z, r2.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r0.w, r2.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r0.zw, null, r0.zzzw
					mul r0.zw, r0.zzzw, l(0.000000, 0.000000, 43758.546875, 43758.546875)
					frc r0.xyzw, r0.xyzw
					mad r0.x, r0.z, l(2.000000), r0.x
					mad r0.z, r0.w, l(2.000000), r0.z
					add r0.x, r0.w, r0.x
					dp2 r1.x, r4.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r1.y, r4.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r1.xy, null, r1.xyxx
					mul r1.xy, r1.xyxx, l(43758.546875, 43758.546875, 0.000000, 0.000000)
					frc r1.xy, r1.xyxx
					mad r0.x, r1.x, l(2.000000), r0.x
					mad r1.x, r0.y, l(2.000000), r1.x
					add r1.x, r1.y, r1.x
					mad r0.x, r0.y, l(-12.000000), r0.x
					mad r0.x, r1.y, l(2.000000), r0.x
					dp2 r1.z, r5.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r1.w, r5.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r1.zw, null, r1.zzzw
					mul r1.zw, r1.zzzw, l(0.000000, 0.000000, 43758.546875, 43758.546875)
					frc r1.zw, r1.zzzw
					add r0.x, r0.x, r1.z
					mad r0.x, r1.w, l(2.000000), r0.x
					add r0.x, r8.y, r0.x
					dp2 r2.x, r7.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r2.y, r7.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r2.xy, null, r2.xyxx
					mul r2.xy, r2.xyxx, l(43758.546875, 43758.546875, 0.000000, 0.000000)
					frc r2.xy, r2.xyxx
					add r0.z, r0.z, r2.x
					mad r0.w, r2.x, l(2.000000), r0.w
					mad r0.z, r0.y, l(2.000000), r0.z
					mad r0.y, r1.y, l(2.000000), r0.y
					add r0.y, r2.y, r0.y
					mad r0.y, r1.w, l(2.000000), r0.y
					mad r0.y, r8.y, l(-12.000000), r0.y
					mad r0.z, r1.y, l(-12.000000), r0.z
					mad r0.z, r2.y, l(2.000000), r0.z
					add r0.z, r1.w, r0.z
					mad r0.z, r8.y, l(2.000000), r0.z
					dp2 r2.x, r9.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r2.z, r9.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r2.xz, null, r2.xxzx
					mul r2.xz, r2.xxzx, l(43758.546875, 0.000000, 43758.546875, 0.000000)
					frc r2.xz, r2.xxzx
					add r0.zw, r0.zzzw, r2.xxxz
					mad r0.w, r1.y, l(2.000000), r0.w
					mad r1.y, r2.y, l(2.000000), r1.y
					mad r0.w, r2.y, l(-12.000000), r0.w
					mul r0.z, r0.z, l(0.083333)
					mad r0.x, r0.x, l(0.041667), r0.z
					dp2 r0.z, r10.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r2.y, r10.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r2.y, null, r2.y
					mul r2.y, r2.y, l(43758.546875)
					frc r2.y, r2.y
					sincos r0.z, null, r0.z
					mul r0.z, r0.z, l(43758.546875)
					frc r0.z, r0.z
					mad r0.w, r0.z, l(2.000000), r0.w
					add r0.z, r0.z, r1.y
					mad r0.z, r8.y, l(2.000000), r0.z
					mad r0.z, r2.x, l(-12.000000), r0.z
					mad r0.z, r2.y, l(2.000000), r0.z
					add r0.w, r8.y, r0.w
					mad r0.w, r2.x, l(2.000000), r0.w
					add r0.w, r2.y, r0.w
					mad r0.x, r0.w, l(0.041667), r0.x
					mad r0.w, r1.z, l(2.000000), r1.x
					mad r1.x, r1.w, l(2.000000), r1.z
					add r1.x, r8.y, r1.x
					mad r0.w, r1.w, l(-12.000000), r0.w
					mad r1.y, r8.y, l(2.000000), r1.w
					mad r0.w, r8.y, l(2.000000), r0.w
					mad r1.z, r2.x, l(2.000000), r8.y
					mad r0.y, r2.x, l(2.000000), r0.y
					add r1.yz, r2.xxyx, r1.yyzy
					dp2 r1.w, r6.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r2.x, r6.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r2.x, null, r2.x
					mul r2.x, r2.x, l(43758.546875)
					frc r2.x, r2.x
					sincos r1.w, null, r1.w
					mul r1.w, r1.w, l(43758.546875)
					frc r1.w, r1.w
					add r0.w, r0.w, r1.w
					mad r1.x, r1.w, l(2.000000), r1.x
					mad r1.x, r2.x, l(-12.000000), r1.x
					mad r0.w, r2.x, l(2.000000), r0.w
					dp2 r1.w, r12.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r2.y, r12.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r2.y, null, r2.y
					mul r2.y, r2.y, l(43758.546875)
					frc r2.y, r2.y
					sincos r1.w, null, r1.w
					mul r1.w, r1.w, l(43758.546875)
					frc r1.w, r1.w
					add r0.w, r0.w, r1.w
					mad r0.x, r0.w, l(0.083333), r0.x
					add r0.y, r0.y, r2.x
					mad r0.w, r2.x, l(2.000000), r1.y
					mad r0.w, r1.w, l(-12.000000), r0.w
					mad r0.w, r2.y, l(2.000000), r0.w
					mad r0.y, r1.w, l(2.000000), r0.y
					add r0.y, r2.y, r0.y
					mad r0.x, r0.y, l(0.166667), r0.x
					add r0.y, r0.z, r1.w
					mad r0.y, r2.y, l(2.000000), r0.y
					dp2 r0.z, r13.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r1.y, r13.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r1.y, null, r1.y
					mul r1.y, r1.y, l(43758.546875)
					frc r1.y, r1.y
					sincos r0.z, null, r0.z
					mul r0.z, r0.z, l(43758.546875)
					frc r0.z, r0.z
					add r0.y, r0.z, r0.y
					mad r0.x, r0.y, l(0.083333), r0.x
					mad r0.y, r1.w, l(2.000000), r1.x
					mad r1.x, r1.w, l(2.000000), r1.z
					mad r1.x, r2.y, l(-12.000000), r1.x
					mad r0.z, r0.z, l(2.000000), r1.x
					add r0.y, r1.y, r0.y
					dp2 r1.x, r11.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r1.y, r11.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r1.xy, null, r1.xyxx
					mul r1.xy, r1.xyxx, l(43758.546875, 43758.546875, 0.000000, 0.000000)
					frc r1.xy, r1.xyxx
					mad r0.y, r1.x, l(2.000000), r0.y
					add r0.yzw, r0.yyzw, r1.yyyx
					mad r0.w, r1.y, l(2.000000), r0.w
					mad r0.x, r0.y, l(0.041667), r0.x
					dp2 r0.y, r14.xyxx, l(12.989800, 78.233002, 0.000000, 0.000000)
					dp2 r1.x, r14.zwzz, l(12.989800, 78.233002, 0.000000, 0.000000)
					sincos r1.x, null, r1.x
					mul r1.x, r1.x, l(43758.546875)
					frc r1.x, r1.x
					sincos r0.y, null, r0.y
					mul r0.y, r0.y, l(43758.546875)
					frc r0.y, r0.y
					add r0.w, r0.y, r0.w
					mad r0.y, r0.y, l(2.000000), r0.z
					add r0.y, r1.x, r0.y
					mad r0.x, r0.w, l(0.083333), r0.x
					mad r0.x, r0.y, l(0.041667), r0.x
					mul o0.y, r0.x, l(0.062500)
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
}